trigger: 'none' # disable CI trigger
pr: 'none' # disable PR trigger

pool:
  vmImage: 'windows-latest' # the AzureFileCopy task requires a Windows agent

parameters:
- name: 'deployType'
  displayName: 'Type of ARM Deployment'
  type: 'string'
  values:
  - 'standard' # for a deployment of the all-in-one ARM Template
  - 'linked' # for a deployment of the Linked ARM Templates
  default: 'standard'

variables:
  azureServiceConnection: 'test-ado-serviceconnection' # Azure DevOps Service Connection for Azure
  sourceAdf: 'adf-test-nn' # name of the source Azure Data Factory instance
  sourceAdfPublishBranch: 'adf_publish'
  destAdf: 'adf-test-new' # name of the destination Azure Data Factory instance
  destAdfRg: 'adf-test-new' # Resource Group for the destination Azure Data Factory instance
  linkedTemplatesStorageAccount: 'storageAccountName' # name of the Storage Account to hold the ARM Linked Templates

resources:
  repositories:
  - repository: 'adfTemplates'
    type: 'github'
    name: 'nnellans/azure-data-factory'
    ref: $(sourceAdfPublishBranch)
    endpoint: 'nnellans' # Azure DevOps Service Connection for GitHub

steps:

- checkout: 'adfTemplates'

#------------------
# If using default Template
#------------------

# perform a what-if deployment
- task: 'AzureCLI@2'
  displayName: 'What-If Deployment for Standard Templates'
  condition: and( succeeded(), eq('${{ parameters.deployType }}', 'standard') )
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    scriptArguments: ''
    inlineScript: |
      az deployment group create `
        --what-if `
        --resource-group $(destAdfRg) `
        --template-file $(System.DefaultWorkingDirectory)\$(sourceAdf)\ARMTemplateForFactory.json `
        --parameters $(System.DefaultWorkingDirectory)\$(sourceAdf)\ARMTemplateParametersForFactory.json

#------------------
# If using Linked Templates
#------------------

# copy the ARM Linked Templates from the ADF repo to an Azure Storage account
- task: 'AzureFileCopy@5'
  name: 'AzureFileCopy'
  displayName: 'Copy Linked Templates to Azure Storage'
  condition: and( succeeded(), eq('${{ parameters.deployType }}', 'linked') )
  inputs:
    azureSubscription: $(azureServiceConnection)
    SourcePath: ''
    Destination: 'AzureBlob'
    storage: $(linkedTemplatesStorageAccount)
    ContainerName: 'linkedTemplates' # will be automatically created if it doesn't exist
    #CleanTargetBeforeCopy: true # default is false
    #sasTokenTimeoutInMinutes: 120 # default is 240

# perform a what-if deployment
- task: 'AzureCLI@2'
  displayName: 'What-If Deployment for Linked Templates'
  condition: and( succeeded(), eq('${{ parameters.deployType }}', 'linked') )
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    scriptArguments: ''
    inlineScript: |
      az deployment group create `
        --what-if
        --subscription blah `
        --resource-group blah `
        --template-file $(System.DefaultWorkingDirectory)/$(sourceAdf)/linkedTemplates/ArmTemplate_master.json`
        --parameters $(System.DefaultWorkingDirectory)/$(sourceAdf)/linkedTemplates/ArmTemplateParameters_master.json`
        